name: Platform
description: Run Freckle Platform commands
inputs:
  github_token:
    description: Personal Access Token to download the platform CLI asset
    required: true
  run:
    description: Script to run
    required: true
outputs: {}
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - -t
    - ${{ inputs.token }}
    - -c
    - ${{ inputs.run }}
